version: '3.8'

services:

  listener:
    build: ./listener_service
    container_name: listener_service
    restart: always
    ports:
      - "5000:5000"
    devices:
      - "/dev/rfcomm0:/dev/rfcomm0"
    depends_on:
      - monitor

  monitor:
    build: ./monitoring_service
    container_name: monitor_service
    restart: always
    ports:
      - "5001:5000"
    privileged: true
    devices:
      - "/dev/vchiq:/dev/vchiq"
    volumes:
      - ./shared_images:/app/Images
      - /run/udev:/run/udev:ro
    depends_on:
      - listener
  
  upload:
    build: ./cloud_communication_service
    container_name: cloud_communication_service
    restart: always
    ports:
      - "5002:5000"
    volumes:
      - ./shared_images:/app/Images
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - DEPLOYMENT_MODE=Cloud
    depends_on:
      - monitor

  trigger_service:
    build: ./led_trigger_service
    container_name: trigger_service
    restart: always
    ports:
      - "5004:5000"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - DEPLOYMENT_MODE=Cloud
