version: '3.8'

services:

  listener:
    build: ./listener_service
    container_name: listener_service
    restart: always
    ports:
      - "5000:5000"
    devices:
      - "/dev/rfcomm0:/dev/rfcomm0"
    depends_on:
      - monitor

  monitor:
    build: ./monitoring_service
    container_name: monitor_service
    restart: always
    ports:
      - "5001:5000"
    privileged: true
    devices:
      - "/dev/vchiq:/dev/vchiq"
      # - "/dev/vchiq"
      # - "/dev/video0"
    volumes:
      - ./shared_images:/app/Images
      # - /opt/vc:/opt/vc
      - /run/udev:/run/udev:ro
    # environment:
    #   - LD_LIBRARY_PATH=/opt/vc/lib
    #   - PYTHONUNBUFFERED=1

  upload:
    build: ./cloud_communication_service
    container_name: cloud_communication_service
    restart: always
    ports:
      - "5002:5000"
    volumes:
      - ./shared_images:/app/Images
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    depends_on:
      - monitor

